---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - "recipe[fixture::port]"
      - "recipe[fixture::service]"
      - "recipe[fixture::masquerade]"

  - name: rich_rule
    run_list:
      - "recipe[fixture::rich_rule]"
